version: '3.8'
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: report
      POSTGRES_PASSWORD: reportpwd
      POSTGRES_DB: reporting
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./reporting/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpwd
    ports:
      - "8080:80"
volumes:
  pgdata:
  mongodata:
  py_analytics:
    build: ../backend/py_analytics
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: service.settings